### ISSUE TITLE
jas.cfg cannot locate

### ISSUE THREAD

**Issue by tarikogut** [jasonpsage/JAS#1]
i installed jas server /usr/local/jas/bin

if i entered command jas finded config/jas.cfg <---- is working now jas
cd /usr/local/jas/bin/
./jas64

if  i entered command jas cannot find config/jas.cfg
 /usr/local/jas/bin/jas64

results : 
Configuration File: usr/local/jas/config/jas.cfg
!! Error(s) Reported by Core_Init !!

**Comment by jasonpsage** [comment]
yea thats definitely a configuration error, not a code change. See /jas/config/jas.cfg - note which paths require trailing slashes like apache.--JAson

-------- Original Message --------
Subject: [JegasCRM] jas.cfg cannot locate (#1)

**Comment by Newlifer** [comment]
I second this.

**Comment by jasonpsage** [comment]
you need to run jas inside the bin folder or the src directory. it looks for ../config/jas.cfg

try:

cd /jas/bin

./jas

-------- Original Message --------
Subject: Re: [JegasCRM] jas.cfg cannot locate (#1)

**Comment by jasonpsage** [comment]
Perhaps this will help. This is how I start jas:

**cd /jas/bin**               or    **cd /jas/src**       (If I compiled it)

**./jas**

JegasCRM/JAS looks for      

**../config/jas.cfg**
